### ISSUE TITLE
Unable to find write path

### ISSUE THREAD

**Issue by moozaad** [mickael9/fac#6]
```
 >fac -v
Traceback (most recent call last):
  File "/usr/bin/fac", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/fac/main.py", line 44, in main
    manager = ModManager(api=api, config=config)
  File "/usr/lib/python3.5/site-packages/fac/mods.py", line 296, in __init__
    self.config.mods_path,
  File "/usr/lib/python3.5/site-packages/fac/files.py", line 178, in mods_path
    return os.path.join(self.factorio_write_path, 'mods')
  File "/usr/lib/python3.5/site-packages/fac/files.py", line 143, in factorio_write_path
    self.config_file
Exception: Can not find the factorio write path.
Please set the write-path variable in /home/steam/.config/fac/config.ini
```

```
> cat ~/.config/fac/config.ini                                                                                                                                                   
[paths]
data-path = /home/steam/factorio/data
write-path = /home/steam/factorio

> pwd
/home/steam/factorio
```

**Comment by mickael9** [comment]
Make sure Factorio was started once so that the write files are created (you should have a mods directory in ~/.factorio)

In your case you normally don't need to edit the config.ini file since ~/.factorio is in the standard path list

**Comment by moozaad** [comment]
Been using factorio for a while. It does run fine from /home/steam/factorio once the config was gone. Just an issue when parsing the config file.

**Comment by mickael9** [comment]
I just tried locally and had the error so there is definitely something wrong here, I'll look into it.

**Comment by mickael9** [comment]
I just did a 0.6 release, this should fix you original issue and your paths shouldn't be ignored from the config file anymore.
